from __future__ import annotations

import csv
from pathlib import Path
from typing import Optional

from .base import FileEntry, Source

API_BASE = "https://api.gdc.cancer.gov"

# Columns present in every GDC manifest (TSV) generated by the portal or
# the `manifest` API endpoint.
REQUIRED_HEADERS = {"id", "filename", "md5", "size"}


class GDCSource(Source):
    name = "gdc"

    def __init__(self, token: Optional[str] = None):
        self.token = token

    @staticmethod
    def sniff(header_fields: list[str]) -> bool:
        return REQUIRED_HEADERS.issubset(set(header_fields))

    def parse_manifest(self, path: Path) -> list[FileEntry]:
        entries = []
        with open(path, newline="") as f:
            reader = csv.DictReader(f, delimiter="\t")
            for row in reader:
                file_id = row["id"].strip()
                entries.append(
                    FileEntry(
                        file_id=file_id,
                        filename=row["filename"].strip(),
                        rel_dir=Path("gdc") / file_id,
                        url=f"{API_BASE}/data/{file_id}",
                        size=int(row["size"]) if row.get("size", "").strip() else None,
                        md5=row.get("md5", "").strip() or None,
                    )
                )
        return entries

    def request_kwargs(self, entry: FileEntry) -> dict:
        headers = {}
        if self.token:
            headers["X-Auth-Token"] = self.token
        return {"headers": headers}
