from __future__ import annotations

import csv
import logging
from pathlib import Path
from typing import Optional

import requests

from .base import FileEntry, Source

log = logging.getLogger("mcdi.download.gdc")

API_BASE = "https://api.gdc.cancer.gov"
FILES_ENDPOINT = f"{API_BASE}/files"

# Columns present in every GDC manifest (TSV) generated by the portal or
# the `manifest` API endpoint.
REQUIRED_HEADERS = {"id", "filename", "md5", "size"}


class GDCSource(Source):
    name = "gdc"

    def __init__(self, token: Optional[str] = None):
        self.token = token

    @staticmethod
    def sniff(header_fields: list[str]) -> bool:
        return REQUIRED_HEADERS.issubset(set(header_fields))

    def parse_manifest(self, path: Path) -> list[FileEntry]:
        entries = []
        with open(path, newline="") as f:
            reader = csv.DictReader(f, delimiter="\t")
            for row in reader:
                file_id = row["id"].strip()
                entries.append(
                    FileEntry(
                        file_id=file_id,
                        filename=row["filename"].strip(),
                        rel_dir=Path("gdc") / file_id,
                        url=f"{API_BASE}/data/{file_id}",
                        size=int(row["size"]) if row.get("size", "").strip() else None,
                        md5=row.get("md5", "").strip() or None,
                    )
                )
        return entries

    def request_kwargs(self, entry: FileEntry) -> dict:
        headers = {}
        if self.token:
            headers["X-Auth-Token"] = self.token
        return {"headers": headers}

    def known_open(self, entries: list[FileEntry], session: requests.Session) -> set[str]:
        """Bulk-query GDC's ``access`` field for every id; no token needed for this.

        This just narrows which entries the per-file pre-flight probe has to
        touch — open files never need the individual round trip.
        """
        ids = [e.file_id for e in entries]
        if not ids:
            return set()
        try:
            resp = session.post(
                FILES_ENDPOINT,
                json={
                    "filters": {"op": "in", "content": {"field": "file_id", "value": ids}},
                    "fields": "file_id,access",
                    "size": len(ids),
                    "format": "JSON",
                },
                timeout=60,
            )
            resp.raise_for_status()
            hits = resp.json()["data"]["hits"]
        except (requests.RequestException, KeyError, ValueError) as exc:
            log.warning("Could not bulk-check GDC access ahead of time (%s); falling back to per-file checks.", exc)
            return set()
        return {h["file_id"] for h in hits if h.get("access") == "open"}
